# Storage Type
# Available values : NONE, MONGO
storageType: "NONE"

# Storage URL if storageType is not NONE (check documentation of the specified storage)
# Example for mongo : storageUrl: "mongodb://localhost:27017/"
storageUrl: ""

# Used for multithreading
# -1 = Use all threads from your computer - 2 (by default we remove 2 threads to not overload computer)
# /!\ You can put the max value if your want but this will use all available resource /!\
maxThreads: -1
